### PR TITLE
Updated Lustre to Spectrum

### PR DESCRIPTION
**Pull request by frobnitzem**
Added one link to ref:\`data-storage-and-transfers\`
and several internal links to “Data Retention, Purge, & Quota Summary”.

Note that the documentation in `data/` states 90 days for Member Work.

### CODE REVIEW

**Comment by grahamlopez** [comment]
@frobnitzem thank you for these updates. A lot of us are at SC right now, but we'll get this reviewed soon. The text changes seem fine.

@gmarkomanolis can you double check this - especially that the table is completely up to date? Even the parts not changed in this PR; it is a good time to verify it.

**Comment by frobnitzem** [comment]
Hi @grahamlopez and @gmarkomanolis.  In regards to checking the consistency of the tables, I noticed a lot of tables containing the same filesystem properties and put them together using jinja templating: https://github.com/olcf/olcf-user-docs/compare/master...frobnitzem:jinja

The change requires adding templating to process ``{{ }}`` sections in all rst files.
I'll send that as a separate PR.

**Comment by gmarkomanolis** [comment]
I will check it.

**Comment by gmarkomanolis** [comment]
I was not familiar with this section under accounts, the policy that I edited is here: https://docs.olcf.ornl.gov/data/policies.html

**Comment by grahamlopez** [comment]
thanks @gmarkomanolis. Let us know what you find out about the footnotes

**Comment by gmarkomanolis** [comment]
I did remove the footnotes so I will merge it

**Pull request merged**
