### PR TITLE
Data section

### PR DESCRIPTION
**Pull request by gmarkomanolis**
Preparing data section, system overview and policy almost done, need to fix a lot of other things, not ready to be merged.

### CODE REVIEW

**Comment by gmarkomanolis** [comment]
Fixes #53

**Comment by grahamlopez** [comment]
> how do you feel about moving the contents of data/burst_buffer.rst into the Summit User Guide?

If we do end up moving it, let's definitely mention it and link to it in the Data Guide. I can imagine plenty of people looking for it there, especially as they are learning about the filesystems in general.

**Comment by gmarkomanolis** [comment]
We can move it but as it was mentioned already just a link in case someone is checking on the data section for the Burst Buffer.

**Comment by grahamlopez** [comment]
Yeah, I'm fine with it in either place, but whichever we choose, the other needs to link to it. Maybe others have a stronger opinion.

**Comment by grahamlopez** [comment]
@jack-morrison i have made some fixes as discussed in the meeting. take a look

**Pull request merged**
