### PR TITLE
Initial documentation for myOLCF self-service portal

### PR DESCRIPTION
**Pull request by admgc**
* Added myOLCF overview and navigation descriptions
* Updated instructions on application processes for existing users
* Added instructions for PIs to process project membership requests

### CODE REVIEW

**Comment by AroSwift** [comment]
All grammer changes from prior work:
1. `year round` should probably be `year-round`
2. `If you need to make further inquiries about your application you may email our Accounts Team at accounts@ccs.ornl.gov.` should probably have a comma: `If you need to make further inquiries about your application, you may email our Accounts Team at accounts@ccs.ornl.gov.`

**Comment by admgc** [comment]
> All grammar changes

Fixed. Thanks, Aaron

**Comment by chrisfuson** [comment]
Looks good.  Just a few thoughts:
- At some point, from a navigation standpoint, I think it would be good to make myOLCF a single page v.s a page per category.
- Under 'What can it do?', items are listed under as you wait on your account.  Is more information needed on how to access the site before you have an account?

**Comment by admgc** [comment]
>  Is more information needed on how to access the site before you have an account?

Good point. I made a couple of those bulleted items links to other pages where I explain those processes in more detail.

**Review by chrisfuson — APPROVED** [review]

**Pull request merged**
