### PR TITLE
[WIP] Adds logo and favicon.

### LINKED ISSUE #6: Add OLCF logo to left-hand navigation
See [Spack docs](https://spack.readthedocs.io/en/latest/) for reference.

### PR DESCRIPTION
**Pull request by jack-morrison**
Fixes #6

### CODE REVIEW

**Comment by grahamlopez** [comment]
So this looks nice. However, from a UI perspective, the logo says "OLCF ..." but actually links to documentation homepage. Confusing?

**Comment by jack-morrison** [comment]
Hm. That's a good point. Maybe we could add a "back to olcf.ornl.gov" button? I think the action of clicking on the RTD logo area should keep a user inside of the docs, but am open to being convinced otherwise.

**Comment by grahamlopez** [comment]
yeah, it is obviously standard for the RTD theme for the icon to take you to the home page, so probably want to keep that. I wonder if we can change the logo image so that is more clear, and we'll have backlinks to OLCF elsewhere in the page(s)

**Comment by jack-morrison** [comment]
I'd be in favor of putting backlinks to olcf.ornl.gov in place of `View Page Source` in the top right of all pages.

I asked @tom-papatheodore about this and he also suggested a change to the logo graphic.

**Comment by grahamlopez** [comment]
sounds fine to me

**Comment by jack-morrison** [comment]
Closing, as this work (and other header/footer integration) is being picked up by Brian Gajus.

**Pull request closed without merging**
