### PR TITLE
ibm-wml-ce: Updates for 1.6.2

### PR DESCRIPTION
**Pull request by bethune-bryant**
Updating the IBM WML CE docs in preparation for 1.6.2 being available on Summit.

fyi @bnemanich

### CODE REVIEW

**Comment by bethune-bryant** [comment]
@jack-morrison @grahamlopez 
After this is merged, how long will it take to go live?

**Comment by jack-morrison** [comment]
@bethune-bryant <= 5min

**Comment by bethune-bryant** [comment]
Okay, after this is merged in we can make 1.6.2 the default.

**Comment by jack-morrison** [comment]
Sounds good to me. @mpbelhorn you good with this plan?

**Comment by grahamlopez** [comment]
@jack-morrison lgtm.

**Comment by mpbelhorn** [comment]
Ready to make the v1.6.2 the default once this is merged.

**Pull request merged**
