### PR TITLE
initial jupyter commit

### PR DESCRIPTION
**Pull request by proutrc**
@secondspass creating this draft pull request to collaborate on.

### CODE REVIEW

**Comment by secondspass** [comment]
Suggested topics and headings:

- [ ] overview of the sidebar buttons
- [ ] overview of the default conda environment
- [ ] how to setup your own custom conda environment

Edit this comment to add more

**Comment by proutrc** [comment]
@secondspass check out the changes. I added a link to the jupyterLab interface docs (that maybe covers some of the suggested topics above?). I also added some very simple directory traversal info and images. Let me know what you think or please feel free to improve.

**Comment by kincl** [comment]
Can we add some documentation about how to shut down your running notebook so you can select another "flavor"?

**Comment by proutrc** [comment]
> Can we add some documentation about how to shut down your running notebook so you can select another "flavor"?

That is a good idea too - can do

**Comment by proutrc** [comment]
> > Can we add some documentation about how to shut down your running notebook so you can select another "flavor"?
> 
> That is a good idea too - can do

This is complete

**Comment by proutrc** [comment]
@kincl @chrisfuson @secondspass 

This is no longer a "Draft" and is ready to be reviewed and merged into olcf:master.

**Review by kincl — APPROVED** [review]
lgtm

**Comment by secondspass** [comment]
Is fine by me

**Pull request merged**
