### PR TITLE
Scorep updated docs with Tabs extension enabled in conf.py

### PR DESCRIPTION
**Pull request by Datawarrior85**

### CODE REVIEW

**Comment by tom-papatheodore** [comment]
@Datawarrior85 I updated `conf.py` and `software/profiling/Scorep.rst` to use sphinx-panels instead of sphinx-tabs. Now I need to actually review the content. Once we've converged on the content of the Score-P page itself, before we merge this PR, I'll still need to:

- Update the contributing section to include the `sphinx-panels` dependency
- Update the Dockerfile in https://gitlab.ccs.ornl.gov/ua/olcf-user-docs-infra to make sure the public docs has access to `sphinx-panels`

**Comment by tom-papatheodore** [comment]
@Datawarrior85 I made edits throughout this PR. Most of them were formatting issues (see my commits), but I did make some changes to the code blocks in a few places (e.g., changed `gfortran` to `mpif90` in the MPI section) - so you might want to read back through the content too. But the content itself should all work correctly now (e.g., there were some links that pointed to your local system). 

Note that I _did not_ test any of the recipes you provided on the actual system - so you might want to double-check these before considering them complete.

So the next steps are:

1. @Datawarrior85 Double check the content as mentioned above.
2. @tom-papatheodore Update the Dockerfile to add `sphinx-panels` (as mentioned in my previous comment) 
3. @tom-papatheodore Ask Ryan Prout to rebuild the docker image.
4. @tom-papatheodore Approve this PR

(One of my commits above already updated the Contributing section to include `sphinx-panels` in local build environments)

**Comment by Datawarrior85** [comment]
Updated ``c++`` with ``cpp``

**Comment by Datawarrior85** [comment]
Need to use ``gfortran`` with Score-P when calling ``-fopenmp``, somewhere under the hood when using ``mpif90`` with ``-fopenmp`` and Score-P it runs into a link error. Without Score-P instrumentation yes ``mpif90`` with ``-fopenmp`` does work and would be the right choice. Under the hood ``mpif90`` uses ``gfortran`` .... check with mpif90 --showme:compiler

**Comment by Datawarrior85** [comment]
Changed the CUDA library to point to ``L${OLCF_CUDA_ROOT}/lib64`` when using NVHPC

**Comment by tom-papatheodore** [comment]
@Datawarrior85 I added `sphinx-panels` to the Dockerfile and rebuilt the image - so `sphinx-panels` will now be available in the build environment for the public docs (just like we had to install the package for our local builds/tests with dropdowns/tabs). 

Now I just need to pull in your latest commits to this PR and make sure everything still works as expected. Are you happy with the current content/functionality of your PR?

**Comment by Datawarrior85** [comment]
pushed latest commit changed  ``mpif90`` for ``mpifort``. Additionally added ``-pthread`` option for ``MPI+OpenMP`` instrumentations

**Comment by Datawarrior85** [comment]
Tested and I am happy with current content and functionality of the latest commit. I think this PR is ready to merge per your approval.

**Pull request merged**
